from __future__ import annotations

from typing import Any


SCHEMA_VERSION = "draft-2026-10-03"

COMMON_OUTPUT_CONTRACT: dict[str, Any] = {
    "type": "object",
    "description": "All tools return the shared CommandResponse envelope.",
    "required": ["ok", "command", "request_id", "backend", "summary", "data", "validation", "errors"],
    "properties": {
        "ok": {"type": "boolean"},
        "command": {"type": "string"},
        "request_id": {"type": "string"},
        "backend": {"type": "string"},
        "summary": {"type": "string"},
        "data": {"type": "object"},
        "validation": {"type": "object"},
        "errors": {"type": "array", "items": {"type": "object"}},
    },
}


def _string(description: str, enum: list[str] | None = None) -> dict[str, Any]:
    schema: dict[str, Any] = {"type": "string", "description": description}
    if enum:
        schema["enum"] = enum
    return schema


def _integer(description: str, minimum: int | None = None, maximum: int | None = None) -> dict[str, Any]:
    schema: dict[str, Any] = {"type": "integer", "description": description}
    if minimum is not None:
        schema["minimum"] = minimum
    if maximum is not None:
        schema["maximum"] = maximum
    return schema


def _boolean(description: str) -> dict[str, Any]:
    return {"type": "boolean", "description": description}


def _array(description: str) -> dict[str, Any]:
    return {"type": "array", "description": description, "items": {"type": "string"}}


def _object_schema(properties: dict[str, Any], required: list[str] | None = None) -> dict[str, Any]:
    merged = {
        "request_id": _string("Optional stable idempotency key for the CLI request."),
        **properties,
    }
    return {
        "type": "object",
        "additionalProperties": False,
        "required": required or [],
        "properties": merged,
    }


def _tool(
    name: str,
    cli_command: str,
    title: str,
    description: str,
    category: str,
    required: list[str] | None = None,
    properties: dict[str, Any] | None = None,
    mutates_document: bool = False,
    requires_wps: bool = False,
    idempotency: str = "Optional request_id is accepted for traceability.",
    cli_example: str | None = None,
    safety_notes: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "name": name,
        "cli_command": cli_command,
        "title": title,
        "description": description,
        "category": category,
        "mutates_document": mutates_document,
        "requires_wps": requires_wps,
        "idempotency": idempotency,
        "input_schema": _object_schema(properties or {}, required),
        "output_contract": COMMON_OUTPUT_CONTRACT,
        "cli_example": cli_example or f"python -m wps_ai_agent_cli {cli_command}",
        "safety_notes": safety_notes or [],
    }


MCP_TOOL_SCHEMAS: tuple[dict[str, Any], ...] = (
    _tool(
        "wps_agent_inspect_env",
        "inspect-env",
        "Inspect WPS environment",
        "Inspect OS, pywin32 availability, and WPS COM ProgID registration.",
        "environment",
    ),
    _tool(
        "wps_agent_wps_process_audit",
        "wps-process-audit",
        "Audit WPS processes",
        "List WPS-related processes and safe cleanup guidance without terminating anything.",
        "environment",
        properties={
            "timeout_seconds": _integer("Timeout for process inspection.", minimum=1),
        },
        cli_example="python -m wps_ai_agent_cli wps-process-audit",
    ),
    _tool(
        "wps_agent_cleanup_plan",
        "cleanup-plan",
        "Build cleanup plan",
        "Build a read-only local cleanup plan with approval-required candidates.",
        "maintenance",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli cleanup-plan",
        safety_notes=[
            "This tool is read-only and never deletes files.",
            "Every cleanup candidate requires explicit user approval before removal.",
        ],
    ),
    _tool(
        "wps_agent_cleanup_approval_manifest",
        "cleanup-approval-manifest",
        "Build cleanup approval manifest",
        "Build a read-only cleanup approval manifest grouped by category.",
        "maintenance",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli cleanup-approval-manifest",
        safety_notes=[
            "This tool is read-only and never deletes files.",
            "Use it to review exact cleanup categories before any separate approval-gated cleanup.",
        ],
    ),
    _tool(
        "wps_agent_artifact_retention_summary",
        "artifact-retention-summary",
        "Summarize artifact retention",
        "Summarize retained local artifacts and approval-required cleanup candidates without deleting anything.",
        "maintenance",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli artifact-retention-summary",
        safety_notes=[
            "This tool is read-only.",
            "It never deletes files and only reports approval-required cleanup candidates.",
        ],
    ),
    _tool(
        "wps_agent_plan",
        "plan",
        "Return roadmap",
        "Return the staged implementation roadmap.",
        "project",
    ),
    _tool(
        "wps_agent_project_status",
        "project-status",
        "Return local project status",
        "Summarize local project state, next task, artifacts, and cleanup posture.",
        "project",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli project-status",
    ),
    _tool(
        "wps_agent_workspace_health",
        "workspace-health",
        "Return workspace health",
        "Summarize local workspace health across project status, cleanup posture, regression evidence, and sync package state.",
        "project",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli workspace-health",
    ),
    _tool(
        "wps_agent_local_handoff_summary",
        "local-handoff-summary",
        "Return local handoff summary",
        "Summarize local handoff readiness across status, health, regression, drift, and package evidence.",
        "project",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli local-handoff-summary",
        safety_notes=[
            "This tool is read-only.",
            "It does not run regression, launch WPS, create packages, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_validation_runbook",
        "validation-runbook",
        "Return validation runbook",
        "Return a read-only local validation runbook without executing the steps.",
        "project",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli validation-runbook",
        safety_notes=[
            "This tool is read-only.",
            "It does not execute commands, launch WPS, create packages, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_documentation_freshness",
        "documentation-freshness",
        "Check documentation freshness",
        "Check current documentation and config references for stale tool counts or next tasks.",
        "project",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli documentation-freshness",
        safety_notes=[
            "This tool is read-only.",
            "It scans documentation and config only; it does not edit files, launch WPS, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_regression_history",
        "regression-history",
        "Summarize regression history",
        "Summarize recent safe and WPS regression artifacts without running regression.",
        "regression",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
            "limit": _integer("Maximum artifacts per profile to include.", minimum=1),
        },
        cli_example="python -m wps_ai_agent_cli regression-history",
        safety_notes=[
            "This tool is read-only.",
            "It reads existing regression artifacts and does not run regression or launch WPS.",
        ],
    ),
    _tool(
        "wps_agent_tasks",
        "tasks",
        "List development tasks",
        "List staged development tasks with optional phase and status filters.",
        "project",
        properties={
            "phase": _string("Optional phase id such as phase0, phase1, or phase2."),
            "status": _string("Optional task status such as next or done."),
        },
        cli_example="python -m wps_ai_agent_cli tasks --phase phase2",
    ),
    _tool(
        "wps_agent_com_smoke",
        "com-smoke",
        "Run COM smoke test",
        "Open, save a copy, and close a WPS Writer, Spreadsheets, or Presentation file.",
        "smoke",
        required=["component", "input", "output"],
        properties={
            "component": _string("WPS component to exercise.", ["writer", "spreadsheets", "presentation"]),
            "input": _string("Input document path."),
            "output": _string("Output copy path."),
            "visible": _boolean("Show WPS during the smoke run."),
        },
        requires_wps=True,
        cli_example="python -m wps_ai_agent_cli com-smoke --component writer --input input.docx --output output.docx",
    ),
    _tool(
        "wps_agent_calc_smoke",
        "calc-smoke",
        "Run spreadsheet calculation smoke test",
        "Verify formula calculation through WPS Spreadsheets.",
        "smoke",
        required=["input", "output"],
        properties={
            "input": _string("Input workbook path."),
            "output": _string("Output workbook path."),
            "timeout_seconds": _integer("Timeout for the WPS spreadsheet COM smoke.", minimum=1),
        },
        requires_wps=True,
    ),
    _tool(
        "wps_agent_convert_smoke",
        "convert-smoke",
        "Run conversion smoke test",
        "Convert a WPS Writer document to PDF and report conversion evidence.",
        "smoke",
        required=["component", "input", "output", "format"],
        properties={
            "component": _string("Component to convert.", ["writer"]),
            "input": _string("Input file path."),
            "output": _string("Output file path."),
            "format": _string("Output format.", ["pdf"]),
        },
        requires_wps=True,
    ),
    _tool(
        "wps_agent_html_render",
        "html-render",
        "Render local HTML",
        "Render local HTML to PDF or PNG using headless Microsoft Edge with local-only resources and JavaScript disabled by default.",
        "conversion",
        required=["input", "output", "format"],
        properties={
            "input": _string("Local .html or .htm source path."),
            "output": _string("New .pdf or .png output path; existing files are never overwritten."),
            "format": _string("Rendered artifact format.", ["pdf", "png"]),
            "page_size": _string("PDF page size.", ["A4", "Letter", "Legal", "Tabloid"]),
            "viewport_width": _integer("Browser viewport width.", minimum=320, maximum=3840),
            "viewport_height": _integer("Browser viewport height.", minimum=240, maximum=2160),
            "timeout_seconds": _integer("Render timeout.", minimum=1, maximum=120),
            "allow_javascript": _boolean("Explicitly enable page scripts; network requests remain blocked."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        idempotency="Optional request_id is accepted for traceability; creates a new artifact and refuses to overwrite an existing output path.",
        cli_example="python -m wps_ai_agent_cli html-render --input page.html --output page.pdf --format pdf",
        safety_notes=[
            "Only local resources under the input HTML directory are allowed; network and other protocols are blocked.",
            "JavaScript is disabled by default. Input is limited to 10 MiB; individual resources to 20 MiB and total local resources to 100 MiB.",
            "Creates a new PDF or PNG and never modifies the source HTML or overwrites an existing output.",
        ],
    ),
    _tool(
        "wps_agent_html_editable",
        "html-editable",
        "Convert HTML to editable Writer content",
        "Map semantic local HTML to editable DOCX paragraphs, headings, lists, tables, hyperlinks, and local images; report CSS fidelity loss.",
        "conversion",
        required=["input", "output"],
        properties={
            "input": _string("Local .html or .htm source path."),
            "output": _string("New .docx output path; existing files are never overwritten."),
            "task_id": _string("Optional task status id."),
        },
        mutates_document=True,
        idempotency="Optional request_id is accepted for traceability; creates a new editable artifact and refuses to overwrite an existing output path.",
        cli_example="python -m wps_ai_agent_cli html-editable --input page.html --output page.docx",
        safety_notes=[
            "Creates a new DOCX artifact; source HTML is unchanged and existing outputs are never overwritten.",
            "Only local images under the HTML directory are embedded; remote images, scripts, and unsupported elements are omitted and reported.",
            "Semantic content is mapped to native editable Word objects; CSS layout is not preserved and is reported as unsupported fidelity.",
        ],
    ),
    _tool(
        "wps_agent_html_roundtrip_plan",
        "html-roundtrip-plan",
        "Validate controlled HTML round-trip identity",
        "Validate owned HTML schema v1 and return a deterministic read-only map from stable object IDs to native object types and indices.",
        "conversion",
        required=["input"],
        properties={"input": _string("Local owned HTML file using wps-agent-html/v1 and stable data-wps-object-id attributes.")},
        safety_notes=[
            "Read-only: does not modify HTML, create a DOCX, launch WPS, or fetch resources.",
            "Rejects missing/duplicate IDs, unsupported ID-bearing elements, CSS and executable content instead of silently losing identity.",
        ],
    ),
    _tool(
        "wps_agent_html_controlled_import",
        "html-controlled-import",
        "Import owned HTML with identity metadata",
        "Convert validated owned HTML into editable DOCX, preserve stable IDs as DOCX bookmarks, and write a mapping sidecar.",
        "conversion",
        required=["input", "output"],
        properties={"input": _string("Owned HTML v1 source."), "output": _string("New DOCX path; existing DOCX or mapping sidecar is never overwritten."), "task_id": _string("Optional task status id.")},
        mutates_document=True,
        idempotency="Optional request_id is accepted for traceability; refuses to overwrite either output artifact.",
        safety_notes=["Source HTML is unchanged; creates a new DOCX and adjacent .wpsmap.json sidecar.", "Rejects invalid schema/IDs and fails closed if mapping metadata cannot be persisted."],
    ),
    _tool(
        "wps_agent_html_roundtrip_verify",
        "html-roundtrip-verify",
        "Verify controlled HTML object identity",
        "Read a DOCX and its mapping sidecar to detect missing, duplicate, or reordered mapped object bookmarks after edits.",
        "conversion",
        required=["docx", "mapping"],
        properties={"docx": _string("Edited DOCX path."), "mapping": _string("Adjacent .wpsmap.json identity sidecar path.")},
        safety_notes=["Read-only; does not modify the DOCX or mapping sidecar and does not launch WPS."],
    ),
    _tool(
        "wps_agent_html_roundtrip_export",
        "html-roundtrip-export",
        "Export controlled DOCX to owned HTML",
        "Serialize a verified controlled DOCX and identity sidecar back to owned HTML v1 while preserving stable object IDs.",
        "conversion",
        required=["docx", "mapping", "output"],
        properties={"docx": _string("Controlled DOCX path."), "mapping": _string("Identity sidecar path."), "output": _string("New .html/.htm output; existing files are never overwritten."), "task_id": _string("Optional task status id.")},
        mutates_document=True,
        idempotency="Optional request_id is accepted for traceability; refuses to overwrite an existing HTML output.",
        safety_notes=["Creates a new HTML artifact only after all mapped identities verify; source DOCX and sidecar remain unchanged.", "Unsupported WordprocessingML elements or untracked content are rejected instead of silently dropped."],
    ),
    _tool(
        "wps_agent_html_batch_convert",
        "html-batch-convert",
        "Batch convert local HTML files",
        "Convert a bounded directory of local HTML files to PDF, PNG, or editable DOCX with per-file isolation and a SHA-256 provenance manifest.",
        "conversion",
        required=["input_dir", "output_dir", "mode"],
        properties={
            "input_dir": _string("Directory containing local .html/.htm files."),
            "output_dir": _string("Output directory outside the input tree; new outputs and manifest are never overwritten."),
            "mode": _string("Output format.", ["pdf", "png", "docx"]),
            "recursive": _boolean("Include nested directories."),
            "task_id": _string("Optional task status id for tracking the batch."),
        },
        mutates_document=True,
        idempotency="Optional request_id is accepted for traceability; refuses to overwrite existing outputs or the batch manifest.",
        safety_notes=[
            "Creates output artifacts only; source files are unchanged. Processes at most 100 HTML files and 500 MiB total input.",
            "Each file is reported independently, and failures do not stop subsequent files. Existing files are never overwritten.",
            "Runs locally without WPS; HTML rendering keeps JavaScript disabled and network isolation enabled by default.",
            "With task_id, progress is updated between files and task-status-update --state cancelled requests cooperative cancellation; completed results remain in the manifest.",
        ],
    ),
    _tool(
        "wps_agent_html_batch_request",
        "html-batch-request",
        "Inspect HTML batch request",
        "Return a recorded HTML batch request state, arguments, manifest path, and recovery guidance without changing files.",
        "batch",
        required=["batch_request_id"],
        properties={"batch_request_id": _string("Original batch conversion request_id to inspect."),
                    "verify": _boolean("Verify current manifest and source/output hashes without modifying state.")},
        safety_notes=["Reads only local request records; does not render or mutate files."],
    ),
    _tool(
        "wps_agent_batch_template_report",
        "batch-template-report",
        "Render a batch report from a local template",
        "Validate a bounded HTML batch conversion manifest and render its summary and per-file provenance into a local Markdown/text or DOCX template.",
        "conversion",
        required=["manifest", "template", "output"],
        properties={
            "manifest": _string("Existing wps-agent-batch-conversion/v1 JSON manifest."),
            "template": _string("Existing local Markdown, text, or DOCX template with supported placeholders."),
            "output": _string("New Markdown/text output for text templates, or .docx for DOCX templates; existing reports are never overwritten."),
            "task_id": _string("Optional task status id for tracking report generation."),
        },
        mutates_document=True,
        idempotency="Optional request_id is accepted for traceability; refuses to overwrite an existing report.",
        safety_notes=[
            "Creates one local report artifact; the manifest and template are unchanged. Template expressions are never executed.",
            "Validates per-file source/output hashes and summary counts before rendering; unknown placeholders are rejected.",
            "Manifest, template, report size, and file count are bounded; output must be a new file.",
        ],
    ),
    _tool(
        "wps_agent_register_document",
        "register-document",
        "Register document",
        "Register a supported local file and return a stable document_id.",
        "documents",
        required=["component", "path"],
        properties={
            "component": _string("Document component.", ["writer", "spreadsheets", "presentation"]),
            "path": _string("Document path to register."),
        },
        cli_example="python -m wps_ai_agent_cli register-document --component writer --path input.docx",
    ),
    _tool(
        "wps_agent_documents",
        "documents",
        "List documents",
        "List registered documents and their current existence status.",
        "documents",
    ),
    _tool(
        "wps_agent_backup_document",
        "backup-document",
        "Create backup",
        "Create a recoverable backup for a registered document_id.",
        "safety",
        required=["document_id"],
        properties={
            "document_id": _string("Registered document_id."),
            "dry_run": _boolean("Preview the backup path without copying."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Creates a filesystem backup under .wps-agent/backups; dry_run previews without copying.",
            "Use before document-changing commands when an explicit backup is needed.",
        ],
    ),
    _tool(
        "wps_agent_list_backups",
        "list-backups",
        "List backups",
        "List recoverable backups, optionally scoped to one document_id.",
        "safety",
        properties={"document_id": _string("Optional registered document_id.")},
    ),
    _tool(
        "wps_agent_restore_backup",
        "restore-backup",
        "Restore backup",
        "Restore a selected backup after first protecting the current file.",
        "safety",
        required=["document_id"],
        properties={
            "document_id": _string("Registered document_id."),
            "backup_name": _string("Backup filename from list-backups."),
            "backup_path": _string("Backup path from list-backups."),
            "dry_run": _boolean("Preview restore without copying."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Restores a registered document from a backup and creates a pre-restore backup before overwriting.",
            "Provide either backup_name or backup_path; dry_run previews without copying.",
        ],
    ),
    _tool(
        "wps_agent_writer_replace",
        "writer-replace",
        "Replace Writer text",
        "Replace body text in a registered WPS Writer document with backup, dry-run, and validation.",
        "writer",
        required=["document_id", "find", "replace"],
        properties={
            "document_id": _string("Registered writer document_id."),
            "find": _string("Text to find."),
            "replace": _string("Replacement text."),
            "dry_run": _boolean("Preview matches without modifying the file."),
            "paragraph_index": _integer("Optional 1-based paragraph index.", minimum=1),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Uses WPS to mutate a registered Writer document and creates a backup before mutation.",
            "Use dry_run before mutation when possible.",
        ],
    ),
    _tool(
        "wps_agent_writer_fill_bookmark",
        "writer-fill-bookmark",
        "Fill Writer bookmark",
        "Fill a unique same-paragraph body bookmark with backup and exact read-back validation.",
        "writer",
        required=["document_id", "bookmark_name", "text"],
        properties={
            "document_id": _string("Registered writer document_id."),
            "bookmark_name": _string("Unique, non-reserved body bookmark name."),
            "text": _string("Text to write into the bookmark range."),
            "dry_run": _boolean("Preview the bookmark target without modifying the file."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Uses WPS to fill a unique same-paragraph body bookmark and creates a backup before mutation.",
            "Rejects missing, ambiguous, cross-paragraph and non-body bookmarks; use dry_run to inspect the target.",
        ],
    ),
    _tool(
        "wps_agent_writer_table_write",
        "writer-table-write",
        "Write Writer table cell",
        "Write text to a table cell in a registered WPS Writer document with backup, dry-run, and validation.",
        "writer",
        required=["document_id", "table_index", "row", "column", "text"],
        properties={
            "document_id": _string("Registered writer document_id."),
            "table_index": _integer("1-based table index.", minimum=1),
            "row": _integer("1-based row index.", minimum=1),
            "column": _integer("1-based column index.", minimum=1),
            "text": _string("Replacement cell text."),
            "dry_run": _boolean("Preview target cell without modifying the file."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Uses WPS to mutate a registered Writer table cell and creates a backup before mutation.",
            "Use dry_run before mutation; table, row, and column are 1-based and validated before write.",
        ],
    ),
    _tool(
        "wps_agent_writer_table_smoke",
        "writer-table-smoke",
        "Smoke Writer table cell update",
        "Run a repeatable WPS Writer table cell update smoke test against an output copy with backup and restore dry-run checks.",
        "smoke",
        required=["input", "output", "table_index", "row", "column", "text"],
        properties={
            "input": _string("Input Writer fixture path."),
            "output": _string("Output copy path."),
            "table_index": _integer("1-based table index.", minimum=1),
            "row": _integer("1-based row index.", minimum=1),
            "column": _integer("1-based column index.", minimum=1),
            "text": _string("Replacement cell text."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating smoke command; request_id should be supplied for traceable child write and restore-check operations.",
        safety_notes=[
            "Copies the input fixture to the requested output path before launching WPS.",
            "Uses WPS to mutate the output Writer table cell, creates a backup, and verifies restore dry-run availability.",
        ],
    ),
    _tool(
        "wps_agent_validate_document",
        "validate-document",
        "Validate document",
        "Run basic validation checks against a registered document.",
        "validation",
        required=["document_id"],
        properties={
            "document_id": _string("Registered document_id."),
            "contains": _string("Expected body text for writer documents."),
            "cell": _string("Cell address for spreadsheet validation."),
            "equals": _string("Expected cell value for spreadsheet validation."),
        },
    ),
    _tool(
        "wps_agent_snapshot_document",
        "snapshot-document",
        "Snapshot document",
        "Return a structural validation snapshot for a registered document.",
        "validation",
        required=["document_id"],
        properties={"document_id": _string("Registered document_id.")},
    ),
    _tool(
        "wps_agent_writer_structure",
        "writer-structure",
        "Inspect Writer structure",
        "Read bounded heading, style, and bookmark structure from a registered DOCX without WPS.",
        "writer",
        required=["document_id"],
        properties={
            "document_id": _string("Registered Writer document_id."),
            "limit": _integer("Maximum items per section.", minimum=1, maximum=200),
            "section": _string("Structure list to inspect.", enum=["all", "headings", "styles", "bookmarks", "warnings"]),
            "offset": _integer("Zero-based offset for a selected section.", minimum=0),
            "bookmark_name": _string("Exact bookmark name; requires bookmarks section."),
            "expected_sha256": _string("Require the DOCX hash from the preceding page."),
            "include_text": _boolean("Read bounded text from a unique supported bookmark."),
            "text_limit": _integer("Maximum returned bookmark text characters.", minimum=1, maximum=4096),
        },
        safety_notes=["Read-only offline OOXML inspection; WPS layout and rendering are not validated."],
    ),
    _tool(
        "wps_agent_writer_structure_parity",
        "writer-structure-parity",
        "Audit Writer structure parity",
        "Compare a controlled DOCX fixture with read-only local WPS Writer observations.",
        "writer",
        properties={
            "run_wps": _boolean("Explicitly launch WPS Writer for this audit."),
            "timeout_seconds": _integer("WPS audit timeout.", minimum=1, maximum=300),
            "scope": _string("Controlled Writer fixture to compare.", enum=["structure", "nested"]),
            "artifact_dir": _string("Local JSON report directory."),
        },
        requires_wps=True,
        safety_notes=["Requires run_wps=true; opens the controlled fixture read-only, writes a local report, and uses no remote Git."],
    ),
    _tool(
        "wps_agent_operation",
        "operation",
        "Get operation",
        "Return a recorded operation by request_id.",
        "operations",
        required=["request"],
        properties={"request": _string("Recorded operation request_id.")},
    ),
    _tool(
        "wps_agent_operations",
        "operations",
        "List operations",
        "List recorded operation ledger entries.",
        "operations",
    ),
    _tool(
        "wps_agent_mutation_request_inspect",
        "mutation-request-inspect",
        "Inspect mutation request",
        "Read the main operation and derived backup evidence without changing files.",
        "operations",
        required=["request"],
        properties={"request": _string("Mutation request_id to inspect.")},
        safety_notes=["Read-only local file identity and ledger inspection; does not launch WPS."],
    ),
    _tool(
        "wps_agent_task_status_create",
        "task-status-create",
        "Create task status",
        "Create a reusable status record for a long-running task.",
        "tasks",
        required=["command", "operation_request_id"],
        properties={
            "task_id": _string("Optional stable task id."),
            "command": _string("Command or workflow being tracked."),
            "operation_request_id": _string("Request id for the tracked operation."),
            "document_id": _string("Optional related document_id."),
            "message": _string("Initial status message."),
            "recovery_guidance": _array("Recovery guidance items."),
        },
    ),
    _tool(
        "wps_agent_task_status_update",
        "task-status-update",
        "Update task status",
        "Update a long-running task status record.",
        "tasks",
        required=["task_id", "state"],
        properties={
            "task_id": _string("Task id to update."),
            "state": _string("New task state.", ["pending", "running", "succeeded", "failed", "cancelled"]),
            "progress_percent": _integer("Progress percentage.", minimum=0, maximum=100),
            "message": _string("Updated status message."),
            "recovery_guidance": _array("Recovery guidance items."),
            "result_ref": _string("Optional operation request id or output reference."),
        },
    ),
    _tool(
        "wps_agent_task_status",
        "task-status",
        "Get task status",
        "Return one long-running task status record.",
        "tasks",
        required=["task_id"],
        properties={"task_id": _string("Task id to return.")},
    ),
    _tool(
        "wps_agent_task_statuses",
        "task-statuses",
        "List task statuses",
        "List long-running task status records.",
        "tasks",
    ),
    _tool(
        "wps_agent_task_recovery",
        "task-recovery",
        "Get recovery playbook",
        "Return a recovery playbook for a long-running task status.",
        "recovery",
        required=["task_id"],
        properties={"task_id": _string("Task id to recover or inspect.")},
    ),
    _tool(
        "wps_agent_task_recovery_playbooks",
        "task-recovery-playbooks",
        "List recovery playbooks",
        "List available long-running task recovery playbooks.",
        "recovery",
    ),
    _tool(
        "wps_agent_mcp_tools",
        "mcp-tools",
        "List MCP tool schemas",
        "List draft MCP tool schemas mapped from CLI commands.",
        "mcp",
        properties={
            "category": _string("Optional tool category filter."),
            "mutates_document": _string("Optional mutation filter.", ["true", "false"]),
        },
    ),
    _tool(
        "wps_agent_mcp_catalog_snapshot",
        "mcp-catalog-snapshot",
        "Summarize MCP tool catalog",
        "Summarize MCP tool catalog counts, categories, WPS requirements, and safety-note coverage.",
        "mcp",
    ),
    _tool(
        "wps_agent_mcp_catalog_drift",
        "mcp-catalog-drift",
        "Check MCP catalog drift",
        "Compare the current MCP catalog against a read-only baseline guard.",
        "mcp",
        properties={
            "guard": _string("Path to MCP catalog guard baseline JSON."),
        },
        cli_example="python -m wps_ai_agent_cli mcp-catalog-drift",
        safety_notes=[
            "This tool is read-only and does not launch WPS.",
            "It reports drift for review instead of mutating the baseline.",
        ],
    ),
    _tool(
        "wps_agent_mcp_tool_schema",
        "mcp-tool-schema",
        "Get MCP tool schema",
        "Return one draft MCP tool schema by MCP tool name or CLI command.",
        "mcp",
        required=["name"],
        properties={"name": _string("MCP tool name or CLI command.")},
    ),
    _tool(
        "wps_agent_mcp_call",
        "mcp-call",
        "Call MCP tool adapter",
        "Invoke a draft MCP tool by mapping JSON arguments to the existing CLI response layer.",
        "mcp",
        required=["name"],
        properties={
            "name": _string("MCP tool name or CLI command."),
            "arguments_json": _string("JSON object of tool arguments."),
        },
    ),
    _tool(
        "wps_agent_mcp_server",
        "mcp-server",
        "Run MCP server prototype",
        "Run a local MCP-compatible JSON-RPC server prototype over stdio.",
        "mcp",
        properties={
            "once_json": _string("Optional single JSON-RPC request for smoke tests."),
        },
    ),
    _tool(
        "wps_agent_mcp_smoke",
        "mcp-smoke",
        "Run MCP server smoke checks",
        "Run repeatable MCP server smoke checks for initialize, tools/list, and tools/call.",
        "mcp",
        properties={
            "expected_min_tools": _integer("Minimum number of tools expected from tools/list.", minimum=1),
            "tool_name": _string("Tool name to exercise through tools/call."),
            "arguments_json": _string("Optional JSON object for a local read-only tool call."),
        },
    ),
    _tool(
        "wps_agent_mcp_config_audit",
        "mcp-config-audit",
        "Audit MCP client config",
        "Audit a local MCP client config and run a configured tools/list smoke check.",
        "mcp",
        properties={
            "config": _string("Path to MCP client config JSON."),
            "server_name": _string("Server key under mcpServers."),
            "expected_min_tools": _integer("Minimum number of tools expected from tools/list.", minimum=1),
            "timeout_seconds": _integer("Timeout for the configured tools/list smoke.", minimum=1),
        },
    ),
    _tool(
        "wps_agent_regression_manifest",
        "regression-manifest",
        "List regression manifest scenarios",
        "List regression manifest scenarios and smoke matrix metadata.",
        "regression",
        properties={
            "manifest": _string("Path to regression manifest JSON."),
            "profile": _string("Optional scenario profile filter."),
            "include_wps": _boolean("Include scenarios that require WPS."),
        },
    ),
    _tool(
        "wps_agent_regression_run",
        "regression-run",
        "Run regression manifest",
        "Run regression scenarios from the manifest.",
        "regression",
        properties={
            "manifest": _string("Path to regression manifest JSON."),
            "profile": _string("Optional scenario profile filter."),
            "include_wps": _boolean("Include scenarios that require WPS."),
            "artifact_dir": _string("Optional directory where a timestamped regression-run JSON artifact will be written."),
        },
    ),
    _tool(
        "wps_agent_local_release_gates",
        "local-release-gates",
        "Run local release gates",
        "Package the workspace, run safe regression, refresh the package, and check release gates in order.",
        "regression",
        safety_notes=["Writes local package and regression artifacts; does not launch WPS or use remote Git."],
    ),
    _tool(
        "wps_agent_regression_evidence",
        "regression-evidence",
        "Summarize regression evidence",
        "Summarize latest safe and WPS regression evidence artifacts without running WPS.",
        "regression",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
        },
        cli_example="python -m wps_ai_agent_cli regression-evidence",
        safety_notes=[
            "This tool is read-only.",
            "It reads existing regression artifacts and does not launch WPS.",
        ],
    ),
    _tool(
        "wps_agent_cloud_sync_package",
        "cloud-sync-package",
        "Create cloud sync package",
        "Create a portable local project package for handoff or optional synchronization.",
        "sync",
        properties={
            "output": _string("Output zip path."),
            "no_latest_artifacts": _boolean("Do not include the latest safe/WPS regression artifacts."),
        },
    ),
    _tool(
        "wps_agent_sync_package_inspect",
        "sync-package-inspect",
        "Inspect sync package",
        "Inspect an existing cloud sync package for root coverage, hash, entry count, and latest regression artifacts.",
        "sync",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
            "package": _string("Package zip path to inspect."),
        },
        cli_example="python -m wps_ai_agent_cli sync-package-inspect",
        safety_notes=[
            "This tool is read-only.",
            "It does not create packages, launch WPS, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_sync_package_summary",
        "sync-package-summary",
        "Summarize sync package",
        "Summarize an existing cloud sync package by top-level directory, artifact entries, and largest files.",
        "sync",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
            "package": _string("Package zip path to summarize."),
            "limit": _integer("Maximum sample, artifact, and largest-entry rows to include.", minimum=0),
        },
        cli_example="python -m wps_ai_agent_cli sync-package-summary",
        safety_notes=[
            "This tool is read-only.",
            "It does not create packages, launch WPS, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_sync_package_manifest",
        "sync-package-manifest",
        "List sync package entries",
        "List entries from an existing cloud sync package with optional prefix filtering.",
        "sync",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
            "package": _string("Package zip path to list."),
            "prefix": _string("Optional zip path prefix to filter, for example docs or src/wps_ai_agent_cli."),
            "limit": _integer("Maximum manifest entries to return.", minimum=0),
        },
        cli_example="python -m wps_ai_agent_cli sync-package-manifest --prefix docs --limit 20",
        safety_notes=[
            "This tool is read-only.",
            "It does not create packages, launch WPS, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_sync_package_coverage",
        "sync-package-coverage",
        "Check sync package coverage",
        "Compare package entries with workspace sync roots using package time as the coverage cutoff.",
        "sync",
        properties={
            "workspace": _string("Workspace root to compare. Defaults to the current directory."),
            "package": _string("Package zip path to compare."),
            "limit": _integer("Maximum missing, extra, and newer-than-package rows to include.", minimum=0),
        },
        cli_example="python -m wps_ai_agent_cli sync-package-coverage",
        safety_notes=[
            "This tool is read-only.",
            "It does not create packages, launch WPS, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_sync_package_readiness",
        "sync-package-readiness",
        "Summarize sync package readiness",
        "Summarize whether an existing cloud sync package is ready for local handoff by combining inspection, summary, and coverage checks.",
        "sync",
        properties={
            "workspace": _string("Workspace root to inspect. Defaults to the current directory."),
            "package": _string("Package zip path to inspect."),
            "limit": _integer("Maximum sample and coverage rows to include.", minimum=0),
        },
        cli_example="python -m wps_ai_agent_cli sync-package-readiness",
        safety_notes=[
            "This tool is read-only.",
            "It does not create packages, launch WPS, delete files, or contact remote Git.",
        ],
    ),
    _tool(
        "wps_agent_scan_dir",
        "scan-dir",
        "Scan directory",
        "Scan a directory for supported WPS files and registration status.",
        "batch",
        required=["path"],
        properties={"path": _string("Directory to scan."), "recursive": _boolean("Scan recursively.")},
    ),
    _tool(
        "wps_agent_batch_report",
        "batch-report",
        "Build batch report",
        "Combine directory scan, registration status, and validation snapshots.",
        "batch",
        required=["path"],
        properties={
            "path": _string("Directory to report on."),
            "recursive": _boolean("Report recursively."),
            "no_snapshots": _boolean("Skip validation snapshots."),
        },
    ),
    _tool(
        "wps_agent_spreadsheet_sheets",
        "spreadsheet-sheets",
        "List spreadsheet worksheets",
        "List worksheet order, names, visibility and used dimensions for a registered workbook.",
        "spreadsheet",
        required=["document_id"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
        },
        safety_notes=[
            "Reads the workbook package without launching WPS or modifying the file.",
            "Worksheet order follows the workbook's stored sheet order.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_read",
        "spreadsheet-read",
        "Read spreadsheet range",
        "Read an A1 range from a registered spreadsheet document.",
        "spreadsheet",
        required=["document_id", "range"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "range": _string("A1 range to read, for example A1:D6."),
            "sheet": _string("Optional sheet name. Defaults to first sheet."),
        },
    ),
    _tool(
        "wps_agent_spreadsheet_inspect",
        "spreadsheet-inspect",
        "Inspect spreadsheet calculation and display",
        "Read formulas and saved cached values, recalculate in WPS memory, and return raw results and displayed text without saving the workbook.",
        "spreadsheet",
        required=["document_id", "range"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "range": _string("Finite A1 range to inspect, for example A1:D6."),
            "sheet": _string("Optional sheet name. Defaults to first sheet."),
        },
        requires_wps=True,
        safety_notes=[
            "Opens the registered workbook read-only and closes it without saving.",
            "Recalculation occurs in memory; saved caches are reported separately from WPS values and display text.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_rename_sheet",
        "spreadsheet-rename-sheet",
        "Rename spreadsheet worksheet",
        "Rename a worksheet with Excel title validation, backup and ordered name read-back.",
        "spreadsheet",
        required=["document_id", "old_name", "new_name"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "old_name": _string("Current worksheet name."),
            "new_name": _string("New worksheet name."),
            "dry_run": _boolean("Validate and preview without backup or WPS."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id is bound to document, source and target worksheet names.",
        safety_notes=[
            "Creates a backup before WPS mutation and verifies the complete ordered worksheet-name list after save.",
            "Rejects invalid or duplicate worksheet names before backup or WPS launch.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_create_sheet",
        "spreadsheet-create-sheet",
        "Create spreadsheet worksheet",
        "Create a worksheet at a 1-based position with title validation, backup and ordered name read-back.",
        "spreadsheet",
        required=["document_id", "name"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "name": _string("New worksheet name."),
            "index": {"type": "integer", "description": "1-based insertion index; defaults to the end."},
            "dry_run": _boolean("Validate and preview without backup or WPS."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id is bound to document, worksheet name, insertion index and dry_run.",
        safety_notes=[
            "Creates a backup before WPS mutation and verifies the complete ordered worksheet-name list after save.",
            "Rejects invalid or duplicate worksheet names and out-of-range positions before backup or WPS launch.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_set_sheet_visibility",
        "spreadsheet-set-sheet-visibility",
        "Set spreadsheet worksheet visibility",
        "Show or hide a worksheet with a visible-sheet safeguard, backup and ordered state read-back.",
        "spreadsheet",
        required=["document_id", "sheet_name", "visible"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "sheet_name": _string("Worksheet to show or hide."),
            "visible": {"type": "string", "enum": ["true", "false"], "description": "Set worksheet visible or hidden."},
            "dry_run": _boolean("Validate and preview without backup or WPS."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id is bound to document, worksheet name, visibility and dry_run.",
        safety_notes=[
            "Creates a backup before WPS mutation and verifies the complete ordered worksheet visibility list after save.",
            "Refuses to hide the last visible worksheet before backup or WPS launch.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_delete_sheet",
        "spreadsheet-delete-sheet",
        "Delete spreadsheet worksheet",
        "Delete a worksheet with last-sheet protection, backup and ordered name read-back.",
        "spreadsheet",
        required=["document_id", "sheet_name"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "sheet_name": _string("Worksheet to delete."),
            "dry_run": _boolean("Validate and preview without backup or WPS."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id is bound to document, worksheet name and dry_run.",
        safety_notes=[
            "Creates a backup before WPS mutation and verifies the complete ordered worksheet-name list after save.",
            "Refuses to delete the final worksheet before backup or WPS launch; dry_run previews the exact resulting order.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_copy_sheet",
        "spreadsheet-copy-sheet",
        "Copy spreadsheet worksheet",
        "Copy a worksheet with title and position validation, backup and ordered name plus sample-cell read-back.",
        "spreadsheet",
        required=["document_id", "source_name", "new_name"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "source_name": _string("Worksheet to copy."),
            "new_name": _string("Name for the copied worksheet."),
            "index": {"type": "integer", "description": "1-based insertion index; defaults to the end."},
            "dry_run": _boolean("Validate and preview without backup or WPS."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id is bound to document, source and new worksheet, index and dry_run.",
        safety_notes=[
            "Creates a backup before WPS mutation and verifies ordered names and a copied cell value after save.",
            "Rejects invalid/duplicate titles and out-of-range positions before backup or WPS launch.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_set_sheet_tab_color",
        "spreadsheet-set-sheet-tab-color",
        "Set worksheet tab color",
        "Set or clear a worksheet tab color with strict hex validation, backup and read-back validation.",
        "spreadsheet",
        required=["document_id", "sheet_name", "color"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "sheet_name": _string("Worksheet whose tab color will change."),
            "color": _string("Hex color in #RRGGBB form, or 'none' to clear it."),
            "dry_run": _boolean("Validate and preview without backup or WPS."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id is bound to document, sheet name, normalized color and dry_run.",
        safety_notes=[
            "Creates a backup before WPS mutation and checks the saved tab color through an independent workbook read-back.",
            "Accepts only #RRGGBB or the explicit 'none' reset value before backup or WPS launch.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_write",
        "spreadsheet-write",
        "Write spreadsheet range",
        "Write a JSON matrix to an A1 range in a registered spreadsheet document.",
        "spreadsheet",
        required=["document_id", "range", "values_json"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "range": _string("A1 range to write, for example A1:B2."),
            "values_json": _string("Rectangular JSON matrix, for example [[1,2],[3,4]]."),
            "sheet": _string("Optional sheet name. Defaults to first sheet."),
            "dry_run": _boolean("Preview write shape without modifying the file."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Uses WPS to mutate a registered spreadsheet and creates a backup before mutation.",
            "Creates a backup before mutation and validates read-back results.",
        ],
    ),
    _tool(
        "wps_agent_spreadsheet_formula_write",
        "spreadsheet-formula-write",
        "Write spreadsheet formulas",
        "Write formulas to an A1 range, recalculate with WPS, and validate cached values.",
        "spreadsheet",
        required=["document_id", "range", "formulas_json", "expected_values_json"],
        properties={
            "document_id": _string("Registered spreadsheet document_id."),
            "range": _string("A1 range to write, for example D4:D6."),
            "formulas_json": _string("Rectangular JSON matrix of formulas."),
            "expected_values_json": _string("Rectangular JSON matrix of expected cached values."),
            "sheet": _string("Optional sheet name. Defaults to first sheet."),
            "dry_run": _boolean("Preview formula write shape without modifying the file."),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Uses WPS to mutate formulas in a registered spreadsheet and creates a backup before mutation.",
            "Use dry_run before mutation when possible and validate cached calculation results after write.",
        ],
    ),
    _tool(
        "wps_agent_presentation_replace",
        "presentation-replace",
        "Replace presentation text",
        "Replace text in a registered presentation with backup, validation, and idempotency.",
        "presentation",
        required=["document_id", "find", "replace"],
        properties={
            "document_id": _string("Registered presentation document_id."),
            "find": _string("Text to find."),
            "replace": _string("Replacement text."),
            "dry_run": _boolean("Preview matches without modifying the file."),
            "slide_index": _integer("Optional 1-based slide index.", minimum=1),
            "task_id": _string("Optional long-running task status id."),
        },
        mutates_document=True,
        requires_wps=True,
        idempotency="Mutating command; request_id should be supplied and is replayed by the operation ledger.",
        safety_notes=[
            "Uses WPS to mutate a registered presentation and creates a backup before mutation.",
            "Use dry_run before mutation when possible and validate replacement results after write.",
        ],
    ),
    _tool(
        "wps_agent_security_audit",
        "security-audit",
        "Audit security boundaries",
        "Audit mutating CLI and MCP tool safety boundaries.",
        "security",
    ),
    _tool(
        "wps_agent_performance_baseline",
        "performance-baseline",
        "Capture performance baseline",
        "Capture runtime and output-size baselines for safe read-only commands.",
        "performance",
    ),
)


def list_mcp_tool_schemas(
    category: str | None = None,
    mutates_document: bool | None = None,
) -> list[dict[str, Any]]:
    schemas = [dict(schema) for schema in MCP_TOOL_SCHEMAS]
    if category:
        schemas = [schema for schema in schemas if schema["category"] == category]
    if mutates_document is not None:
        schemas = [schema for schema in schemas if schema["mutates_document"] is mutates_document]
    return schemas


def get_mcp_tool_schema(name: str) -> dict[str, Any] | None:
    for schema in MCP_TOOL_SCHEMAS:
        if schema["name"] == name or schema["cli_command"] == name:
            return dict(schema)
    return None


def list_mcp_tool_categories() -> list[str]:
    return sorted({schema["category"] for schema in MCP_TOOL_SCHEMAS})
